GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6563dd4e91abbcfa4d5bb971

###

POST http://localhost:3000/subscribers
Content-Type: application/json

 {
      "name": "test",
      "subscribedToChannel": "test"
    }



###
DELETE http://localhost:3000/subscribers/655d14c2e255580ba2170bb1

###
PATCH  http://localhost:3000/subscribers/6563dd4e91abbcfa4d5bb971
Content-Type: application/json

 {
      "name": "alozno",
      "subscribedToChannel": "alonzo TV"
    }
